ARG BASE_IMAGE="ghcr.io/gbraad-homelab/private-base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

# php base
RUN dnf install -y php php-fpm php-mysqlnd php-bcmath \
    php-gd php-intl php-ldap php-mbstring php-pdo \
    php-process php-soap php-opcache php-xml \
    php-gmp php-pecl-apcu php-pecl-zip mod_ssl hostname \
    && dnf clean all \
    && rm -rf /var/cache/yum

# install nextcloud
RUN curl -fsSL https://download.nextcloud.com/server/releases/nextcloud-30.0.4.tar.bz2 -o /tmp/nextcloud.tar.bz2 \
    && tar -xjf /tmp/nextcloud.tar.bz2 --strip-components=1 -C /var/www/html/ \
    && rm -f /tmp/nextcloud.tar.bz2 \
    && chown apache /var/www/html/apps/ \
    && chown apache /var/www/html/config/

# systemd
RUN systemctl enable httpd
ENTRYPOINT ["/sbin/init"]
