name: build container (bootc)
run-name: building container (bootc)

on:
  workflow_dispatch:

jobs:
  build:
    name: build-containers-bootc
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - nextcloud (bootc)
        run: |
          podman build -t ghcr.io/gbraad-homelab/nextcloud-bootc \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-dotfiles/almalinux-bootc" \
            --build-arg=BASE_VERSION="9" \
            -f containers/Containerfile .

      - name: Login to ghcr.io
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to ghcr.io - nextcloud (bootc)
        run: |
          podman push ghcr.io/gbraad-homelab/nextcloud-bootc
